# Dataset generation configuration

output_folder: "./data/output"
input_folder: "./data/input"
chunk_sizes_seconds: 5
sample_rate: 48000

dataset_length_goal_minutes: 60*100 #100 hours
target_lufs: -20
validation_data_percentage: 0.3

augmentations:
  - eq_high_cut
  - eq_low_cut
  - eq_mid_boost
  - hard_compression
